CREATE TABLE GHSFL.Clubs
(
    ClubId INT NOT NULL IDENTITY (1,1) CONSTRAINT pkClubs PRIMARY KEY,
    ClubName NVARCHAR(100) NOT NULL
);

CREATE TABLE GHSFL.Fencers
(
    FencerId BIGINT NOT NULL IDENTITY (1,1) CONSTRAINT pkFencers PRIMARY KEY,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    ClubId INT NOT NULL CONSTRAINT fkFencersOnClub REFERENCES GHSFL.Clubs (ClubId),
    Points INT NOT NULL DEFAULT 0,
    Gender CHAR NOT NULL,
    DateCreated DATETIME DEFAULT GETDATE()
);

CREATE TABLE GHSFL.Users
(
    UserId NVARCHAR(256) NOT NULL CONSTRAINT pkUsers PRIMARY KEY,
    UserName NVARCHAR(100) NOT NULL,
    PermissionLevel SMALLINT NOT NULL DEFAULT 0,
    EmailAddress NVARCHAR(320) NOT NULL,
    ClubId INT NULL CONSTRAINT fkUsersOnClub REFERENCES GHSFL.Clubs (ClubId)
);

CREATE TABLE GHSFL.Rounds
(
    RoundNum INT NOT NULL CONSTRAINT pkRounds PRIMARY KEY,
    RoundDate DATETIME NOT NULL
);

CREATE TABLE GHSFL.Rosters
(
    RosterId BIGINT NOT NULL IDENTITY(1000,1) CONSTRAINT pkRosters PRIMARY KEY,
    ClubId INT NOT NULL CONSTRAINT fkRostersOnClub REFERENCES GHSFL.Clubs (ClubId),
    RoundNumber INT NOT NULL CONSTRAINT fkRostersOnRound REFERENCES GHSFL.Rounds (RoundNum),
    SubmittedTime DATETIME NOT NULL DEFAULT GETDATE(),
    SubmittedById NVARCHAR(256) NOT NULL CONSTRAINT fkRostersOnUsers REFERENCES GHSFL.Users (UserId),
    Gender CHAR NOT NULL
);

CREATE TABLE GHSFL.RosterFencers
(
    RosterId BIGINT NOT NULL CONSTRAINT fkRosterFencersOnRosters REFERENCES GHSFL.Rosters (RosterId),
    FencerId BIGINT NOT NULL CONSTRAINT fkRosterFencersOnFencers REFERENCES GHSFL.Fencers (FencerId),

    CONSTRAINT pkRosterFencers PRIMARY KEY (RosterId, FencerId)
);

CREATE TYPE GHSFL.uttRosterFencer AS TABLE
(
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL
);
